# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 108d6f33dcba0f39e82d76a60769962f53f34f7efe701e94e403d5e7292c48ae10223e66108088350b459e2a439b219509737e12f59f79a97707a3ab8eb38f35

test:
  secret_key_base: 010a483a6c9091acc383f08f9686154abc9ed428df0f052ebae572bcae9729fe52f56ddf554e0e643e06e1fed29f3437fba037225456dd8728ce7de7f6a2f770

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
